[package]
name = "heapsize_derive"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { path = "../../.." }
#quote = "0.5"
quote = { git = 'https://github.com/dtolnay/quote' }
