[package]
name = "syn"
version = "0.4.0" # don't forget to update version in readme
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Nom parser for Rust items"
repository = "https://github.com/dtolnay/item"
include = ["Cargo.toml", "src/**/*.rs"]

[features]
default = ["parsing", "printing"]
parsing = ["nom"]
printing = ["quote"]

[dependencies]
nom = { version = "1.2.4", optional = true }
quote = { version = "0.1.1", optional = true }
