[package]
name = "syn"
version = "0.11.11" # don't forget to update version in readme for breaking changes
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Nom parser for Rust source code"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/syn/"
categories = ["development-tools::procedural-macro-helpers"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
publish = false # this branch contains breaking changes

[features]
default = ["parsing", "printing", "clone-impls"]
aster = []
full = []
parsing = ["unicode-xid", "synom/parsing"]
printing = ["quote", "synom/printing"]
visit = []
fold = []
clone-impls = []
extra-traits = []

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote', optional = true }
proc-macro2 = { git = 'https://github.com/alexcrichton/proc-macro2' }
unicode-xid = { version = "0.0.4", optional = true }
synom = { version = "0.11", path = "synom", default-features = true }

[dev-dependencies]
syntex_pos = "0.58"
syntex_syntax = "0.58"
tempdir = "0.3.5"
walkdir = "1.0.1"
