[workspace]
members = ["example", "trace-var"]

[patch.crates-io]
proc-macro2-next = { git = "https://github.com/alexcrichton/proc-macro2", branch = "next" }
quote-next = { git = "https://github.com/dtolnay/quote" }
