[package]
name = "synom"
version = "0.11.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Stripped-down Nom parser used by Syn"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/synom/"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
unicode-xid = "0.0.4"
