[package]
name = "synom"
version = "0.11.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Stripped-down Nom parser used by Syn"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/synom/"
categories = ["development-tools::procedural-macro-helpers"]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
unicode-xid = "0.0.4"

[dev-dependencies.syn]
version = "0.11"
path = ".."
features = ["parsing", "full"]
default-features = false
