[package]
name = "dump-syntax"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies.syn]
path = "../.."
default-features = false
features = ["parsing", "full", "extra-traits"]

[dependencies.proc-macro2]
version = "0.4.27"
features = ["span-locations"]

[[bin]]
name = "dump-syntax"
path = "main.rs"

[workspace]
